export type CameraStatus = 'active' | 'offline' | 'alert'
export type LockStatus = 'locked' | 'unlocked'

export interface Vehicle {
  id: string
  name: string
  vin: string
  soc: number
  range: number
  rangeUnit: 'km' | 'mi'
  lockStatus: LockStatus
  cameraStatus: CameraStatus
  lastSeen: string
  lastSeenAlert: boolean
  alertCount: number
  statusLine1: string
  statusLine2: string
  inService: boolean
  coordinates: [number, number]
}

export const vehicles: Vehicle[] = [
  {
    id: 'rapunzel',
    name: 'Rapunzel',
    vin: 'YNQJEPICJFV109803',
    soc: 19,
    range: 65,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'offline',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 0,
    statusLine1: 'In Tesla Service',
    statusLine2: 'Orinda',
    inService: true,
    coordinates: [-122.225, 37.883],
  },
  {
    id: 'coco',
    name: 'Coco',
    vin: 'NFINQHTZFNC470428',
    soc: 61,
    range: 207,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'alert',
    lastSeen: '10h',
    lastSeenAlert: false,
    alertCount: 3,
    statusLine1: '3505 20th Street',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.419, 37.759],
  },
  {
    id: 'eeeyore',
    name: 'Eeeyore',
    vin: 'BCEIMMVCCKQ717104',
    soc: 56,
    range: 190,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'alert',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 3,
    statusLine1: 'Golden Gate Bridge',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.478, 37.819],
  },
  {
    id: 'woody',
    name: 'Woody',
    vin: 'PWBCFOWHKKL690076',
    soc: 98,
    range: 333,
    rangeUnit: 'mi',
    lockStatus: 'locked',
    cameraStatus: 'alert',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 2,
    statusLine1: '3500 Callan Boulevard',
    statusLine2: 'Daly City',
    inService: false,
    coordinates: [-122.469, 37.679],
  },
  {
    id: 'edna',
    name: 'Edna',
    vin: 'TYFTNLLCEZX632527',
    soc: 60,
    range: 204,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'offline',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 1,
    statusLine1: '255 King Street',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.395, 37.778],
  },
  {
    id: 'wall-e',
    name: 'Wall-E',
    vin: 'GOBKCYQDJQP162543',
    soc: 59,
    range: 201,
    rangeUnit: 'mi',
    lockStatus: 'locked',
    cameraStatus: 'offline',
    lastSeen: '10h',
    lastSeenAlert: false,
    alertCount: 0,
    statusLine1: '1 Christmas Tree Point Road',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.453, 37.743],
  },
  {
    id: 'mei-lee',
    name: 'Mei Lee',
    vin: 'PZDBGYPQNGS113912',
    soc: 9,
    range: 31,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'alert',
    lastSeen: 'May 23',
    lastSeenAlert: true,
    alertCount: 0,
    statusLine1: '1202 Mariner Drive',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.398, 37.789],
  },
  {
    id: 'mater',
    name: 'Mater',
    vin: 'LBHQXWZOYPW100287',
    soc: 55,
    range: 187,
    rangeUnit: 'mi',
    lockStatus: 'unlocked',
    cameraStatus: 'offline',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 0,
    statusLine1: '1312 Encinal Avenue',
    statusLine2: 'Alameda',
    inService: false,
    coordinates: [-122.241, 37.765],
  },
  {
    id: 'olaf',
    name: 'Olaf',
    vin: 'ACUTCXIRFYS255903',
    soc: 57,
    range: 194,
    rangeUnit: 'km',
    lockStatus: 'locked',
    cameraStatus: 'alert',
    lastSeen: '9h',
    lastSeenAlert: false,
    alertCount: 0,
    statusLine1: '2402 Balboa Street',
    statusLine2: 'San Francisco',
    inService: false,
    coordinates: [-122.485, 37.776],
  },
]
